version: "3.9"
services:
  web:
    build:
      context: web
    volumes:
      - "./web/app/static:/app/app/samples/static" # временно, чтобы можно было менять html без перезапуска докера

  file-generator:
    build:
      context: file-generator
    volumes:
      - "./file-generator/out:/app/out"

  nginx:
    hostname: $APP_HOSTNAME
    build: nginx/.
    ports:
      - "8080:80"
    env_file:
      - ".env"
#  db:
#    image: postgres:14.5
#    restart: always
#    ports:
#      - "15432:5432"
#    env_file:
#      - ".env"
#    volumes:
#      - "./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"

#      - "pgdata:/var/lib/postgresql/data"

#  rabbitmq:
#    hostname: $RABBIT_HOSTNAME
#    image: rabbitmq:management
#    ports:
#      - "15672:15672"
#    env_file:
#      - ".env"
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 30s
#      timeout: 30s

#      retries: 3
#
#  redis:
#    hostname: $CACHE_HOST
#    image: redis
#    env_file:
#      - ".env"

#volumes:
#  pgdata: